#端口号
server:
  port: 5000


#连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_system
    username: root
    password: 123456
  jdbc:
    template:
      query-timeout: 3
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#mybatis配置规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml           #全局配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml    #sql映射文件位置

#支付宝-沙箱
alipay:
  appId: 1111 #设置自己的
  #协议(固定)
  protocol: https
  #域名
  gatewayHost: openapi.alipaydev.com
  #签名类型(固定)
  signType: RSA2
  #应用私钥(不能有空格)
  merchantPrivateKey:  1111 #设置自己的
  #支付宝公钥(不能有空格)
  alipayPublicKey:  1111 #设置自己的
  #异步通知地址
  #notifyUrl: http://localhost:5000/alipay/notifycall
  notifyUrl: http://localhost:8080/myReader
  #同步通知地址
  returnUrl: http://localhost:5000/alipay/returncall
  #退款异常地址
  errorUrl: http://localhost:8080/myReader
  #退款成功地址
  refundUrl: http://localhost:8080/myReader
  #中途退出地址
  quitUrl: http://localhost:8080/
#我们的个人配置
ourConfig:
  collectionAccount:  1111 #设置自己的

